// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Application.Models;

public partial class AutoGraderDBContext : DbContext
{
    public AutoGraderDBContext(DbContextOptions<AutoGraderDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Rule> Rules { get; set; }

    public virtual DbSet<Submission> Submissions { get; set; }

    public virtual DbSet<Violation> Violations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Rule>(entity =>
        {
            entity.HasKey(e => e.RuleId).HasName("PK__Rules__110458E2D1AA5CA1");

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Pattern).HasMaxLength(255);
            entity.Property(e => e.Severity).HasMaxLength(50);
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("PK__Submissi__449EE125B2870CAB");

            entity.Property(e => e.CheckedAt).HasColumnType("datetime");
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ZipFileName).HasMaxLength(255);
        });

        modelBuilder.Entity<Violation>(entity =>
        {
            entity.HasKey(e => e.ViolationId).HasName("PK__Violatio__18B6DC08D2C7A539");

            entity.Property(e => e.FilePath).HasMaxLength(500);
            entity.Property(e => e.Message).HasMaxLength(1000);

            entity.HasOne(d => d.Rule).WithMany(p => p.Violations)
                .HasForeignKey(d => d.RuleId)
                .HasConstraintName("FK__Violation__RuleI__45F365D3");

            entity.HasOne(d => d.Submission).WithMany(p => p.Violations)
                .HasForeignKey(d => d.SubmissionId)
                .HasConstraintName("FK__Violation__Submi__44FF419A");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}