// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Application.Models;

public partial class Submission
{
    public int SubmissionId { get; set; }

    public string ZipFileName { get; set; }

    public DateTime? UploadedAt { get; set; }

    public DateTime? CheckedAt { get; set; }
    [JsonIgnore]
    public virtual ICollection<Violation> Violations { get; set; } = new List<Violation>();
}