// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Application.Models;

public partial class Submission
{
    public int SubmissionId { get; set; }

    public string ZipFileName { get; set; }

    public DateTime? UploadedAt { get; set; }

    public DateTime? CheckedAt { get; set; }

    // Student relationship
    public int? StudentId { get; set; }
    public virtual Student? Student { get; set; }

    // Solution naming validation results
    public bool? IsSolutionNameValid { get; set; }

    [MaxLength(500)]
    public string? SolutionValidationMessage { get; set; }

    [MaxLength(500)]
    public string? SolutionFilePath { get; set; }

    [JsonIgnore]
    public virtual ICollection<Violation> Violations { get; set; } = new List<Violation>();
}