// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Application.Models;

public partial class Violation
{
    public int ViolationId { get; set; }

    public int? SubmissionId { get; set; }

    public int? RuleId { get; set; }

    public string FilePath { get; set; }

    public string Message { get; set; }
    [JsonIgnore]
    public virtual Rule Rule { get; set; }
    [JsonIgnore]
    public virtual Submission Submission { get; set; }
}